project_id = "melgpvpplocdxlefthcu"

[functions.ai-text-generation]
verify_jwt = true

[functions.generate-prescription-pdf-simple]
verify_jwt = true

[functions.download-prescription]
verify_jwt = true

[functions.cleanup-templates]
verify_jwt = true

[functions.send-sms-notification]
verify_jwt = true

[functions.google-translate]
verify_jwt = false

[functions.bhashini-speech-to-text]
verify_jwt = false

[functions.bhashini-text-to-speech]
verify_jwt = false

[functions.bhashini-translate]
verify_jwt = false

[functions.speech-to-text]
verify_jwt = false

[functions.text-to-speech]
verify_jwt = false