project_id = "melgpvpplocdxlefthcu"

[functions.ai-text-generation]
verify_jwt = true

[functions.generate-prescription-pdf-simple]
verify_jwt = true

[functions.download-prescription]
verify_jwt = true

[functions.cleanup-templates]
verify_jwt = true

[functions.send-sms-notification]
verify_jwt = true