
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Download, Clock, CheckCircle, Stethoscope, AlertCircle, FileText } from "lucide-react";
import { useToast } from "@/hooks/use-toast";

interface PrescriptionStatusProps {
  request: {
    id: string;
    status: 'pending' | 'in_progress' | 'completed';
    prescription_required: boolean;
    is_referral?: boolean;
    prescription?: {
      id: string;
      medications: string;
      instructions: string;
      pdf_url?: string;
      created_at: string;
    } | null;
  };
}

const PrescriptionStatus = ({ request }: PrescriptionStatusProps) => {
  const [isDownloading, setIsDownloading] = useState(false);
  const { toast } = useToast();

  const handleViewPrescription = async () => {
    if (!request.prescription) return;
    
    setIsDownloading(true);
    try {
      // If PDF URL exists, open it directly
      if (request.prescription.pdf_url) {
        window.open(request.prescription.pdf_url, '_blank');
        return;
      }

      // If no PDF URL, show a message that PDF is being generated
      toast({
        title: "PDF Not Ready",
        description: "The prescription PDF is being generated by your doctor. Please check back in a few minutes.",
        variant: "destructive",
      });
    } catch (error) {
      console.error('Error handling prescription:', error);
      toast({
        title: "Error", 
        description: "Failed to open prescription",
        variant: "destructive",
      });
    } finally {
      setIsDownloading(false);
    }
  };

  const isReferral = !request.prescription_required;

  if (request.status === 'completed' && request.prescription) {
    return (
      <Button
        variant="default"
        size="sm"
        onClick={handleViewPrescription}
        disabled={isDownloading}
        className="bg-green-600 hover:bg-green-700"
      >
        <Download className="h-4 w-4 mr-1" />
        {isDownloading ? 'Loading...' : isReferral ? 'View Referral' : 'View Prescription'}
      </Button>
    );
  }

  if (request.status === 'completed' && !request.prescription) {
    return (
      <Button
        variant="outline"
        size="sm"
        disabled
        className="text-orange-600 border-orange-200"
      >
        <Clock className="h-4 w-4 mr-1" />
        {isReferral ? 'Generating Referral' : 'Generating Prescription'}
      </Button>
    );
  }

  if (request.status === 'pending') {
    return (
      <Badge variant="outline" className="text-yellow-600 border-yellow-200 bg-yellow-50">
        <Clock className="h-3 w-3 mr-1" />
        Awaiting Doctor Review
      </Badge>
    );
  }

  if (request.status === 'in_progress') {
    return (
      <Badge variant="outline" className="text-blue-600 border-blue-200 bg-blue-50">
        <Stethoscope className="h-3 w-3 mr-1" />
        Doctor Reviewing
      </Badge>
    );
  }

  return null;
};

export default PrescriptionStatus;
