// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://melgpvpplocdxlefthcu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1lbGdwdnBwbG9jZHhsZWZ0aGN1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzMTE3NzIsImV4cCI6MjA3MTg4Nzc3Mn0._Bw5RlU6R5q7LIBBfuJ2JdMTsXZ5v-G1ogGNfXfq3a4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});